### ISSUE TITLE
Polyfill breaks again

### ISSUE THREAD

**Issue by silencej** [adobe/generator-tsx#69]
# Bug Report

## Describe the bug

On IE11, an error shows as in the screenshot. The same codes work well in Chrome and Firefox.

The IE console error is

```
DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
localhost:11207
HTML1300: Navigation occurred.
localhost:11207

SCRIPT5079: Cannot modify non-writable property 'length'
4.chunk.js (39279,13)
The above error occurred in one of your React components:
    in Unknown (created by Context.Consumer)
    in Route (at App.tsx:26)
    in Switch (at App.tsx:25)
    in Suspense (at App.tsx:24)
    in App (at src/index.tsx:27)
    in Router (created by BrowserRouter)
    in BrowserRouter (at createProviders.tsx:26)
    in IntlProvider (at createProviders.tsx:22)
    in Provider (at createProviders.tsx:18)
    in Unknown (at createProviders.tsx:21)
    in Unknown (at src/index.tsx:26)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
The development server has disconnected.
Refresh the page if necessary.
TypeError: Object doesn't support property or method 'repeat'
   {
      [functions]: ,
      __proto__: { },
      description: "Object doesn't support property or method 'repeat'",
      message: "Object doesn't support property or method 'repeat'",
      name: "TypeError",
      number: -2146827850,
      stack: "TypeError: Object doesn't support property or method 'repeat'
   at Anonymous function (Unknown script code:1:105285)
   at i (Unknown script code:1:105071)
   at ee (Unknown script code:1:288639)
   at Yu (Unknown script code:1:197888)
   at No (Unknown script code:1:210278)
   at Gi (Unknown script code:1:235769)
   at $i (Unknown script code:1:236156)
   at Ta (Unknown script code:1:243056)
   at ka (Unknown script code:1:242436)
   at Ea (Unknown script code:1:241457)",
      Symbol()_9.yxk4rhhbw55: undefined,
      Symbol(react.concurrent_mode)_r.yxk4rhhbw55: undefined,
      Symbol(react.context)_q.yxk4rhhbw55: undefined,
      Symbol(react.element)_k.yxk4rhhbw55: undefined,
      Symbol(react.forward_ref)_s.yxk4rhhbw55: undefined,
      Symbol(react.fragment)_m.yxk4rhhbw55: undefined,
      Symbol(react.lazy)_v.yxk4rhhbw55: undefined,
      Symbol(react.memo)_u.yxk4rhhbw55: undefined,
      Symbol(react.portal)_l.yxk4rhhbw55: undefined,
      Symbol(react.profiler)_o.yxk4rhhbw55: undefined,
      Symbol(react.provider)_p.yxk4rhhbw55: undefined,
      Symbol(react.strict_mode)_n.yxk4rhhbw55: undefined,
      Symbol(react.suspense)_t.yxk4rhhbw55: undefined
   }

SCRIPT438: Object doesn't support property or method 'repeat'
script block (26) (1,242617)
Unhandled promise rejection TypeError: Cannot modify non-writable property 'length'
   "Unhandled promise rejection"
   {
      [functions]: ,
      __proto__: { },
      description: "Cannot modify non-writable property 'length'",
      message: "Cannot modify non-writable property 'length'",
      name: "TypeError",
      number: -2146823209,
      stack: "TypeError: Cannot modify non-writable property 'length'
   at defineProperty (http://localhost:11207/static/js/4.chunk.js:23979:3)
   at mimicFn (http://localhost:11207/static/js/1.chunk.js:266042:7)
   at module.exports (http://localhost:11207/static/js/1.chunk.js:266099:5)
   at Anonymous function (http://localhost:11207/static/js/1.chunk.js:270250:3)
   at createCommonjsModule (http://localhost:11207/static/js/1.chunk.js:230234:3)
   at Anonymous function (http://localhost:11207/static/js/1.chunk.js:270236:1)
   at ./node_modules/prettier/index.js (http://localhost:11207/static/js/1.chunk.js:229979:29)
   at __webpack_require__ (http://localhost:11207/static/js/bundle.js:787:12)
   at fn (http://localhost:11207/static/js/bundle.js:150:13)
   at ./src/components/Legacy/js/app/viewer.js (http://localhost:11207/static/js/2.chunk.js:3458:22)
   at __webpack_require__ (http://localhost:11207/static/js/bundle.js:787:12)
   at fn (http://localhost:11207/static/js/bundle.js:150:13)
   at ./src/components/Legacy/js",
      Symbol()_5.qwjdeh4i5vk: undefined,
      Symbol(allowStale)_16.qwjdeh4i5l: undefined,
      Symbol(cache)_1b.qwjdeh4i5l: undefined,
      Symbol(child-nodes)_10.qwjdeh4i5l: undefined,
      Symbol(cursor)_11.qwjdeh4i5l: undefined,
      Symbol(cursor)_z.qwjdeh4i5lt: undefined,
      Symbol(dispose)_18.qwjdeh4i5l: undefined,
      Symbol(length)_14.qwjdeh4i5l: undefined,
      Symbol(lengthCalculator)_15.qwjdeh4i5l: undefined,
      Symbol(lruList)_1a.qwjdeh4i5l: undefined,
      Symbol(max)_13.qwjdeh4i5l: undefined,
      Symbol(maxAge)_17.qwjdeh4i5l: undefined,
      Symbol(node-ignore)_12.qwjdeh4i5l: undefined,
      Symbol(noDisposeOnSet)_19.qwjdeh4i5l: undefined,
      Symbol(react.async_mode)_x.qwjdeh4i5lt: undefined,
      Symbol(react.concurrent_mode)_s.qwjdeh4i5yt: undefined,
      Symbol(react.context)_r.qwjdeh4i5yt: undefined,
      Symbol(react.element)_l.qwjdeh4i5yt: undefined,
      Symbol(react.forward_ref)_t.qwjdeh4i5yt: undefined,
      Symbol(react.fragment)_n.qwjdeh4i5yt: undefined,
      Symbol(react.lazy)_w.qwjdeh4i5lt: undefined,
      Symbol(react.memo)_v.qwjdeh4i5yt: undefined,
      Symbol(react.portal)_m.qwjdeh4i5yt: undefined,
      Symbol(react.profiler)_p.qwjdeh4i5yt: undefined,
      Symbol(react.provider)_q.qwjdeh4i5yt: undefined,
      Symbol(react.strict_mode)_o.qwjdeh4i5yt: undefined,
      Symbol(react.suspense)_u.qwjdeh4i5yt: undefined,
      Symbol(util.promisify.custom)_y.qwjdeh4i5lt: undefined
   }
```

The codes are:

```tsx
// These must be the first lines in src/index.js
import 'react-app-polyfill/ie11'
import 'react-app-polyfill/stable'
import 'proxy-polyfill'

import React, { lazy, Suspense } from 'react'
import Helmet from 'react-helmet'
import { Route, Switch } from 'react-router-dom'
import { FormattedMessage } from 'react-intl'

// import Nav from '../Nav'
import Spinner from '../Spinner'

const Legacy = lazy(() => import('../Legacy'))
const NotFound = lazy(() => import('../NotFound'))

// Add this to show a nav bar.
// 		<Nav />

const App: React.SFC = () => (
	<>
		<FormattedMessage id="page.image.title">
			{title => (
				<Helmet>
					<title>{title}</title>
				</Helmet>
			)}
		</FormattedMessage>
		<Suspense fallback={<Spinner />}>
			<Switch>
				<Route path="/" exact component={Legacy} />
				<Route component={NotFound} />
			</Switch>
		</Suspense>
	</>
)

export default App
```

**Comment by silencej** [comment]
I am chasing down the bug in IE. Turns out the exception is thrown when `Object.defineProperty(memoizedFunc, 'length', ...)` in IE while it fails silently in Chrome. It's from prettifier so I am curious what in the end causes this failure.

![ieLength](https://user-images.githubusercontent.com/1061428/66793367-ad35db00-ef2f-11e9-9976-1785fe99a3ad.PNG)

**Comment by jedmao** [comment]
Yeah, that doesn't look at all familiar to me. The first issue reported does look a polyfill related issue, but It looks to me like you have the appropriate polyfills loading though.

You know what else you might want to try is [`@loadable/component`](https://www.smooth-code.com/open-source/loadable-components/).

**Comment by silencej** [comment]
@jedmao Thanks for the recommendation. Will look into it when needing SSR.
And good news is, through `git bisect`, I finally found the culprit: one colleague adds `import { util } from 'prettier'` (I thought it was by the VS Code). I remove this line, IE11 support is back again~
